### ISSUE TITLE
CLJS: known symbols report as unresolved

### ISSUE THREAD

**Issue by ingesolvoll** [brcosta/clj-stuff-plugin#4]
Seeing some strange behaviour using Cursive + clojure extras + clj-kondo. A number of vars are reported as unresolved, while they are clearly not. Only inside cursive, not in clj-kondo CLI

![image](https://user-images.githubusercontent.com/426347/149205374-406ae386-456f-4121-827f-1055c288145f.png)

Context: https://clojurians.slack.com/archives/CHY97NXE2/p1642013162080500

**Comment by borkdude** [comment]
If you send the filename including the extension with the `:filename` argument, then clj-kondo can infer that this is a CLJS file and the warning should go away.

**Comment by borkdude** [comment]
Should be solved on master already.

**Comment by brcosta** [comment]
Solved on 0.4.5 (already in the marketplace)
