### ISSUE TITLE
println to stdout is suppressed

### ISSUE THREAD

**Issue by mikeananev** [brcosta/clj-stuff-plugin#7]
Problem description: println output to stdout is suppressed when using `clojure-extras` eval functions.

Steps to reproduce:
1. Run JVM REPL in terminal
2. Connect to remote REPL (nrepl) in Cursive
3. Eval code `(println "Hello world!")` using `clojure-extras` eval functions.
4. I see result of evaluation `=> nil` in pop-up window, but can't see printed "Hello world!" string neither in terminal, nor in Cursive REPL window.

Expected behaviour:
I see result  of evaluation `=> nil` in pop-up window, but also see `Hello world!` in terminal or Cursive REPL window or in pop-up window.

BTW, Cursive eval functions works as expected, no suppression is found

**Comment by brcosta** [comment]
Thanks for reporting, should be fixed on master, I'm waiting for jetbrains to approve it, should be in the marketplace shortly :)
